### ISSUE TITLE
Confusion about fucntion "build_camera_matrices"

### ISSUE THREAD

**Issue by Xiaoxi-Liang** [xg-chu/GAGAvatar#28]
Hi, thank you for your amazing work!  I am really confused when I learn details about how you build vallina 3DGS format camera_matrices. I am a rookie in this field and in my opinion, "view matrix" is world2camera transformation and "cam_matrix" is camera2world transformation (I am sure for this because you get camera position through "cam_pos = cam_matrix[:, :3, 3]") . So, why getting view matrix (in function get_world_to_view_matrix) do not need some operations like transpose or inverse?  What I missed or do you change something in GS rendering processs?

Below are your codes:
```

   def build_camera_matrices(cam_matrix, focal_x, focal_y):

    def get_projection_matrix(fov_x, fov_y, z_near=0.01, z_far=100, device='cpu'):
        K = torch.zeros(4, 4, device=device)
        z_sign = 1.0
        K[0, 0] = 1.0 / math.tan((fov_x / 2))
        K[1, 1] = 1.0 / math.tan((fov_y / 2))
        K[3, 2] = z_sign
        K[2, 2] = z_sign * z_far / (z_far - z_near)
        K[2, 3] = -(z_far * z_near) / (z_far - z_near)
        return K

    def get_world_to_view_matrix(transforms):
        assert transforms.shape[-2:] == (3, 4)
        viewmatrix = transforms.new_zeros(transforms.shape[0], 4, 4)
        for i in range(4):
            viewmatrix[:, i, i] = 1.0
        viewmatrix[:, :3, :3] = transforms[:, :3, :3]
        viewmatrix[:, 3, :3] = transforms[:, :3, 3]
        viewmatrix[:, :, :2] *= -1.0
        return viewmatrix

    def get_full_projection_matrix(viewmatrix, fov_x, fov_y):
        proj_matrix = get_projection_matrix(fov_x, fov_y, device=viewmatrix.device)
        full_proj_matrix = viewmatrix @ proj_matrix.transpose(0, 1)
        return full_proj_matrix

    fov_x = 2 * math.atan(1.0 / focal_x)
    fov_y = 2 * math.atan(1.0 / focal_y)
    view_matrix = get_world_to_view_matrix(cam_matrix)
    full_proj_matrix = get_full_projection_matrix(view_matrix, fov_x, fov_y)
    cam_pos = cam_matrix[:, :3, 3]
    return view_matrix, full_proj_matrix, cam_pos
```

**Comment by xg-chu** [comment]
Thank you for your attention to our work 🤩 and sorry for the late reply.
Since I used pytorch3d to optimize the camera so I follow it: where camera pose is the combination of R and T, and R/T is defined as right multiply form, different from many library [(PyTorch3D Camera)](https://pytorch3d.readthedocs.io/en/latest/modules/renderer/cameras.html#pytorch3d.renderer.cameras.get_world_to_view_transform).
So actually I need to form cam_pos as $[R.trans(), T]$ or $\[R/T\]$ to follow the normal definition of camera matrix, but cam_pos now is $[R, T]$.
You can try to use pytorch3d.renderer.cameras.get_world_to_view_transform and see how is the results. ^_^
